In [40]:
import numpy as np
import pandas as pd

df = pd.read_csv('data/data.csv',encoding='latin-1')

In [41]:
df.info()
df.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [42]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

change id to str type, date to date type

In [43]:
df['CustomerID'] = df['CustomerID'].astype('Int64')
df['CustomerID'] = df['CustomerID'].astype('string')
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [44]:
df['CustomerID'].nunique()

4372

In [45]:
df.duplicated().sum()

np.int64(5268)

In [46]:
df = df.drop_duplicates()

save returned InvoiceNo as a single df

In [47]:
returns_df = df[df['InvoiceNo'].str[0] == 'C']
df = df[df['InvoiceNo'].str[0] != 'C']

In [48]:
neg_qty = df[df['Quantity'] <= 0]
neg_price = df[df['UnitPrice'] <= 0]
print(len(neg_qty))
print(len(neg_price))

1336
2512

In [49]:
neg_price.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,<NA>,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,<NA>,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,<NA>,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,<NA>,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,<NA>,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,<NA>,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,<NA>,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,<NA>,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,<NA>,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,<NA>,United Kingdom

In [50]:
neg_qty.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,<NA>,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,<NA>,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,<NA>,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,<NA>,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,<NA>,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,<NA>,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,<NA>,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,<NA>,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,<NA>,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,<NA>,United Kingdom

3853 rows of error price/quantity in total, most of them have unitprice = 0 and no customerID, decide to delete.

In [51]:
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]

In [52]:
df['CustomerID'].isna().sum()

np.int64(132186)

a very large amount of number, use fillna().

In [53]:
df[df['CustomerID'] == '00000']

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [54]:
df['CustomerID'] = df['CustomerID'].fillna('00000')
df[df['CustomerID'] == '00000']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,00000,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,00000,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,00000,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,00000,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,2010-12-01 14:32:00,1.66,00000,United Kingdom
...,...,...,...,...,...,...,...,...
541536,581498,85099B,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,00000,United Kingdom
541537,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,2011-12-09 10:26:00,4.13,00000,United Kingdom
541538,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,00000,United Kingdom
541539,581498,85174,S/4 CACTI CANDLES,1,2011-12-09 10:26:00,10.79,00000,United Kingdom
541540,581498,DOT,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,00000,United Kingdom

In [55]:
df['Description'] = df['Description'].str.strip().str.upper()

In [56]:
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

In [57]:
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['Day'] = df['InvoiceDate'].dt.day
df['Weekday'] = df['InvoiceDate'].dt.weekday
df['Hour'] = df['InvoiceDate'].dt.hour
df['Minute'] = df['InvoiceDate'].dt.minute

In [58]:
df['Y-M'] = df['InvoiceDate'].dt.to_period('M')

In [59]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Weekday,Hour,Minute,Y-M
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,1,2,8,26,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,2,8,26,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,1,2,8,26,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,2,8,26,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,2,8,26,2010-12

In [60]:
df = df.set_index(df['InvoiceDate']).sort_index()

In [61]:
df.loc['2011-3']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Weekday,Hour,Minute,Y-M
InvoiceDate,,,,,,,,,,,,,,,,
2011-03-01 08:30:00,545220,21955,DOORMAT UNION JACK GUNS AND ROSES,2,2011-03-01 08:30:00,7.95,14620,United Kingdom,15.90,2011,3,1,1,8,30,2011-03
2011-03-01 08:30:00,545220,48194,DOORMAT HEARTS,2,2011-03-01 08:30:00,7.95,14620,United Kingdom,15.90,2011,3,1,1,8,30,2011-03
2011-03-01 08:30:00,545220,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-03-01 08:30:00,1.65,14620,United Kingdom,19.80,2011,3,1,1,8,30,2011-03
2011-03-01 08:30:00,545220,22139,RETROSPOT TEA SET CERAMIC 11 PC,3,2011-03-01 08:30:00,4.95,14620,United Kingdom,14.85,2011,3,1,1,8,30,2011-03
2011-03-01 08:30:00,545220,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,4,2011-03-01 08:30:00,3.75,14620,United Kingdom,15.00,2011,3,1,1,8,30,2011-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011-03-31 19:54:00,548548,22423,REGENCY CAKESTAND 3 TIER,1,2011-03-31 19:54:00,12.75,17781,United Kingdom,12.75,2011,3,31,3,19,54,2011-03
2011-03-31 19:54:00,548548,21361,LOVE LARGE WOOD LETTERS,7,2011-03-31 19:54:00,12.75,17781,United Kingdom,89.25,2011,3,31,3,19,54,2011-03
2011-03-31 19:55:00,548549,84763,ZINC FINISH 15CM PLANTER POTS,100,2011-03-31 19:55:00,1.06,16365,United Kingdom,106.00,2011,3,31,3,19,55,2011-03
2011-03-31 19:55:00,548549,22222,CAKE PLATE LOVEBIRD WHITE,1,2011-03-31 19:55:00,4.95,16365,United Kingdom,4.95,2011,3,31,3,19,55,2011-03
2011-03-31 19:55:00,548549,22776,SWEETHEART CAKESTAND 3 TIER,1,2011-03-31 19:55:00,9.95,16365,United Kingdom,9.95,2011,3,31,3,19,55,2011-03

In [62]:
daily_sale = df.resample('D')['TotalPrice'].sum()
weekly_sale = df.resample('W')['TotalPrice'].sum()
monthly_sale = df.resample('MS')['TotalPrice'].sum()
print(daily_sale.head(5))
print(weekly_sale.head(5))
print(monthly_sale.head(5))

InvoiceDate
2010-12-01    58776.79
2010-12-02    47629.42
2010-12-03    46898.63
2010-12-04        0.00
2010-12-05    31364.63
Freq: D, Name: TotalPrice, dtype: float64
InvoiceDate
2010-12-05    184669.47
2010-12-12    329108.22
2010-12-19    215357.04
2010-12-26     92318.00
2011-01-02         0.00
Freq: W-SUN, Name: TotalPrice, dtype: float64
InvoiceDate
2010-12-01    821452.730
2011-01-01    689811.610
2011-02-01    522545.560
2011-03-01    716215.260
2011-04-01    536968.491
Freq: MS, Name: TotalPrice, dtype: float64

In [63]:
customers = df[df['CustomerID'] != '00000']
customers.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Month,Day,Weekday,Hour,Minute,Y-M
InvoiceDate,,,,,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,1,2,8,26,2010-12
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,2,8,26,2010-12
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,1,2,8,26,2010-12
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,2,8,26,2010-12
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,2,8,26,2010-12

In [64]:
FirstBuy = customers.groupby('CustomerID')['InvoiceDate'].min()
LastBuy = customers.groupby('CustomerID')['InvoiceDate'].max()

In [65]:
CountryStats = df.groupby('Country').agg(
    orders = ('InvoiceNo','nunique'),
    customers = ('CustomerID','nunique'),
    sales = ('TotalPrice','sum')
).sort_values('sales', ascending=False)
CountryStats.head(5)

                orders  customers        sales
Country
United Kingdom   18019       3921  9001744.094
Netherlands         94          9   285446.340
EIRE               288          4   283140.520
Germany            457         94   228678.400
France             392         88   209625.370

In [66]:
print(df.groupby('InvoiceNo').agg({
    'Quantity':'sum',
    'TotalPrice':'sum'
}).sort_values('Quantity', ascending=False).head(10))

print(df.groupby('InvoiceNo').agg({
    'Quantity':'sum',
    'TotalPrice':'sum'
}).sort_values('TotalPrice', ascending=False).head(10))

           Quantity  TotalPrice
InvoiceNo
581483        80995   168469.60
541431        74215    77183.60
556917        15049    22775.93
563076        14730    19150.66
574941        14149    52940.94
576365        13956    50653.91
572035        13392    20277.92
567423        12572    31698.16
552883        12266    14415.74
563614        12196    21880.44
           Quantity  TotalPrice
InvoiceNo
581483        80995   168469.60
541431        74215    77183.60
574941        14149    52940.94
576365        13956    50653.91
556444           60    38970.00
567423        12572    31698.16
556917        15049    22775.93
572209         1920    22206.00
567381         6760    22104.80
563614        12196    21880.44

In [67]:
print(df.groupby('Weekday')['InvoiceNo'].count().sort_values(ascending=False))

print(df.groupby('Hour')['InvoiceNo'].count().sort_values(ascending=False))

Weekday
3    100213
1     98726
0     92466
2     91467
4     79667
6     62339
Name: InvoiceNo, dtype: int64
Hour
12    75986
15    75665
13    69993
14    65057
11    55420
16    52992
10    47597
9     33684
17    27426
8      8797
18     7676
19     3427
20      778
7       379
6         1
Name: InvoiceNo, dtype: int64

pivot table

In [68]:
monthly_country = df.pivot_table(
    index='Y-M',
    columns='Country',
    values='TotalPrice',
    aggfunc='sum'
)
monthly_country

Country,Australia,Austria,Bahrain,Belgium,Brazil,Canada,Channel Islands,Cyprus,Czech Republic,Denmark,...,RSA,Saudi Arabia,Singapore,Spain,Sweden,Switzerland,USA,United Arab Emirates,United Kingdom,Unspecified
Y-M,,,,,,,,,,,,,,,,,,,,,
2010-12,965.35,277.20,205.74,1809.91,NaN,NaN,363.53,1587.07,NaN,1281.50,...,NaN,NaN,NaN,1843.73,3834.30,1304.92,NaN,NaN,746082.220,NaN
2011-01,9017.71,NaN,NaN,1200.20,NaN,NaN,675.58,547.50,NaN,NaN,...,NaN,NaN,2053.07,10086.09,3486.32,4231.23,NaN,NaN,559975.830,NaN
2011-02,14695.42,518.36,NaN,2181.07,NaN,NaN,1784.71,4334.24,549.26,399.22,...,NaN,145.92,NaN,2114.50,509.50,2654.92,NaN,889.24,428986.620,NaN
2011-03,17223.99,1708.12,NaN,3351.98,NaN,140.54,3509.33,938.39,NaN,3978.99,...,NaN,NaN,NaN,5363.15,4720.58,1870.23,NaN,NaN,584810.780,NaN
2011-04,771.60,680.78,NaN,1989.48,1143.6,NaN,293.00,NaN,NaN,NaN,...,NaN,NaN,8209.58,1785.65,809.10,2076.94,383.95,NaN,475677.631,299.10
2011-05,13638.41,1249.43,548.40,2732.40,NaN,534.24,1207.24,NaN,NaN,515.70,...,NaN,NaN,NaN,3257.60,2681.98,3610.01,NaN,NaN,638104.890,1055.87
2011-06,25187.77,NaN,NaN,4274.82,NaN,1171.46,2060.03,1109.32,NaN,3261.15,...,NaN,NaN,NaN,3333.21,832.00,7904.15,NaN,NaN,618345.530,185.78
2011-07,4964.38,1191.95,NaN,2475.57,NaN,1768.58,NaN,NaN,NaN,376.24,...,NaN,NaN,3949.32,7620.77,6802.09,3990.76,NaN,NaN,600919.071,1419.11
2011-08,22489.20,1516.08,NaN,3554.02,NaN,51.56,4886.88,NaN,NaN,213.15,...,NaN,NaN,NaN,3342.41,1390.36,4969.89,NaN,NaN,606784.930,531.03
2011-09,5106.73,NaN,NaN,4208.02,NaN,NaN,1323.75,196.35,NaN,4570.16,...,NaN,NaN,NaN,5189.24,4575.21,8284.86,NaN,1013.04,895098.642,284.30
2011-10,17150.53,1043.78,NaN,5685.38,NaN,NaN,2623.32,4350.32,277.48,1490.76,...,1002.31,NaN,7067.32,8636.94,5766.16,8050.73,2311.20,NaN,935404.140,NaN
2011-11,7242.72,1329.78,NaN,6315.76,NaN,NaN,1514.77,439.66,NaN,2699.57,...,NaN,NaN,NaN,8669.06,2722.23,8118.96,NaN,NaN,1319934.070,965.75
2011-12,NaN,683.20,NaN,1417.73,NaN,NaN,198.40,NaN,NaN,168.90,...,NaN,NaN,NaN,316.21,238.00,NaN,885.24,NaN,591619.740,NaN

In [69]:
total_sales = df['TotalPrice'].sum()
avg_order_value = total_sales / df['InvoiceNo'].nunique()
print(avg_order_value)

533.171883967936

In [70]:
monthly = df.groupby('Y-M')['TotalPrice'].sum().to_frame('Sales')
monthly['MoM'] = monthly['Sales'].pct_change()
print(monthly)

               Sales       MoM
Y-M
2010-12   821452.730       NaN
2011-01   689811.610 -0.160254
2011-02   522545.560 -0.242481
2011-03   716215.260  0.370627
2011-04   536968.491 -0.250269
2011-05   769296.610  0.432666
2011-06   760547.010 -0.011374
2011-07   718076.121 -0.055843
2011-08   757841.380  0.055377
2011-09  1056435.192  0.394006
2011-10  1151263.730  0.089763
2011-11  1503866.780  0.306275
2011-12   637790.330 -0.575900

use transform to get price ratio

In [71]:
df['invoice_price'] = df.groupby('InvoiceNo')['TotalPrice'].transform('sum')
df['ratio'] = df['TotalPrice'] / df['invoice_price']
df['ratio']

InvoiceDate
2010-12-01 08:26:00    0.109977
2010-12-01 08:26:00    0.146205
2010-12-01 08:26:00    0.158137
2010-12-01 08:26:00    0.146205
2010-12-01 08:26:00    0.146205
                         ...
2011-12-09 12:50:00    0.040890
2011-12-09 12:50:00    0.050511
2011-12-09 12:50:00    0.066546
2011-12-09 12:50:00    0.066546
2011-12-09 12:50:00    0.059531
Name: ratio, Length: 524878, dtype: float64

In [72]:
sold = df.groupby('StockCode')['Quantity'].sum().reset_index(name='sold_qty')
returned = returns_df.groupby('StockCode')['Quantity'].sum().abs().reset_index(name='returned_qty')
sold_and_returned = pd.merge(sold, returned, on='StockCode', how='left')
sold_and_returned['returned_qty'] = sold_and_returned['returned_qty'].fillna(0)
sold_and_returned['return_rate'] = sold_and_returned['returned_qty'] / sold_and_returned['sold_qty']
sold_and_returned[sold_and_returned['return_rate'] > 0].sort_values('return_rate', ascending=False)

         StockCode  sold_qty  returned_qty  return_rate
3915             S         2          60.0    30.000000
3900     AMAZONFEE         2          32.0    16.000000
162          20703         1           7.0     7.000000
391          21144         5          12.0     2.400000
3902  BANK CHARGES        12          25.0     2.083333
...            ...       ...           ...          ...
1372         22489      9719           2.0     0.000206
1100         22188      4870           1.0     0.000205
933          21982      7173           1.0     0.000139
80           17003     23020           3.0     0.000130
1438         22560      8144           1.0     0.000123

[1931 rows x 4 columns]

In [73]:
rfm = customers.groupby('CustomerID').agg(
    frequency = ('InvoiceNo', 'nunique'),
    monetary = ('TotalPrice', 'sum')
)
rfm['recency'] = (df['InvoiceDate'].max() - LastBuy).dt.days
rfm.head(5)

            frequency  monetary  recency
CustomerID
12346               1  77183.60      325
12347               7   4310.00        1
12348               4   1797.24       74
12349               1   1757.55       18
12350               1    334.40      309

compete every customers' rfm score

In [74]:
rfm['M'] = pd.qcut(rfm['monetary'], 5, labels=[1,2,3,4,5]).astype(int)
rfm['R'] = pd.qcut(rfm['recency'], 5, labels=[5,4,3,2,1]).astype(int)
rfm['F'] = pd.qcut(rfm['frequency'].rank(method='first'), 5, labels=[1,2,3,4,5]).astype(int)
rfm['RFM_score'] = rfm['M']+rfm['R']+rfm['F']

In [75]:
rfm

            frequency  monetary  recency  M  R  F  RFM_score
CustomerID
12346               1  77183.60      325  5  1  1          7
12347               7   4310.00        1  5  5  5         15
12348               4   1797.24       74  4  2  4         10
12349               1   1757.55       18  4  4  1          9
12350               1    334.40      309  2  1  1          4
...               ...       ...      ... .. .. ..        ...
18280               1    180.60      277  1  1  2          4
18281               1     80.82      180  1  1  2          4
18282               2    178.05        7  1  5  3          9
18283              16   2045.53        3  4  5  5         14
18287               3   1837.28       42  4  3  4         11

[4338 rows x 7 columns]

In [76]:
monthly.to_csv('outputs/monthly_sales.csv')
CountryStats.to_csv('outputs/country_stats.csv')
rfm.to_csv('outputs/rfm.csv')